### ISSUE TITLE
Evaluate RK3568 reboot, WDT and  PCI nvme storage on BSP/Mainline LINUX and u-boot

### ISSUE THREAD

**Issue by Suniel24** [edgeble/dhruva-stream#1]
Check whether:
1. reset, WDT and nvme storage are working in BSP u-boot
2. reboot, WDT and nvme storage are working in BSP Linux
3. reset, WDT and nvme storage are working in u-boot mainline
4. reboot, WDT and nvme storage are working in Linux mainline

**Comment by Suniel24** [comment]
1.
PCI NVME test not required
2.
reboot and WDT are working in all combinations:
log(odriod u-boot + linux-next):
https://gist.github.com/Suniel24/3865478a3d634390a7944298c68c9c58

**Comment by openedev** [comment]
Great.
